name: Bug report
description: Report a bug so we can fix it.
labels: ["pending triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear, concise description of the bug.
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide the minimal steps to reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected-actual
    attributes:
      label: Expected vs. actual behavior
      description: What you expected to happen vs. what actually happened.
      placeholder: |
        Expected: ...
        Actual: ...
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / screen recording
      description: Optional, but helpful for UI issues.
  - type: dropdown
    id: environment
    attributes:
      label: Browser / OS / environment
      description: Select the closest match.
      options:
        - Chrome / Windows
        - Chrome / macOS
        - Chrome / Linux
        - Firefox / Windows
        - Firefox / macOS
        - Firefox / Linux
        - Safari / macOS
        - Edge / Windows
        - Mobile / iOS
        - Mobile / Android
        - Other
    validations:
      required: true
